# Generated by Django 4.1.7 on 2023-03-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shioaji_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='exchange',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
