# Generated by Django 4.1.7 on 2023-03-23 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shioaji_app', '0003_kbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbar',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kbars', to='shioaji_app.stock'),
        ),
    ]
