# Generated by Django 4.1.7 on 2023-05-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shioaji_app', '0005_industry_stock_industries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('institution_type', models.CharField(choices=[('foreign', '外資'), ('investment_trust', '投信'), ('proprietary', '自營')], max_length=20)),
                ('shares', models.IntegerField(default=0)),
                ('trade_date', models.DateField()),
            ],
        ),
    ]
