# Generated by Django 4.1.7 on 2023-06-04 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shioaji_app', '0006_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='shioaji_app.stock'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='trade_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('net', 'Net')], max_length=4),
        ),
    ]
